<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('permissions')->insert([
          ['id' => '1',
          'key' => 'browse_users',
          'module_id' => 1,
          'display_name' => 'Browse'
        ],['id' => '2',
          'key' => 'edit_users',
          'module_id' => 1,
          'display_name' => 'Edit'
        ],['id' => '3',
          'key' => 'add_users',
          'module_id' => 1,
          'display_name' => 'Add'
        ],['id' => '4',
          'key' => 'delete_users',
          'module_id' => 1,
          'display_name' => 'Delete'
        ],['id' => '5',
          'key' => 'read_users',
          'module_id' => 1,
          'display_name' => 'Read'
        ],['id' => '6',
          'key' => 'browse_roles',
          'module_id' => 2,
          'display_name' => 'Browse'
        ],['id' => '7',
          'key' => 'edit_roles',
          'module_id' => 2,
          'display_name' => 'Edit'
        ],['id' => '8',
          'key' => 'add_roles',
          'module_id' => 2,
          'display_name' => 'Add'
        ],['id' => '9',
          'key' => 'delete_roles',
          'module_id' => 2,
          'display_name' => 'Delete'
        ],['id' => '10',
          'key' => 'view_roles',
          'module_id' => 2,
          'display_name' => 'View'
        ],['id' => '11',
          'key' => 'browse_product',
          'module_id' => 3,
          'display_name' => 'Browse Product'
        ],['id' => '12',
          'key' => 'view_product_product',
          'module_id' => 3,
          'display_name' => 'View Product'
        ],['id' => '13',
          'key' => 'add_product_product',
          'module_id' => 3,
          'display_name' => 'Create Product'
        ],['id' => '14',
          'key' => 'edit_product_product',
          'module_id' => 3,
          'display_name' => 'Edit Product'
        ],['id' => '15',
          'key' => 'browse_unit_product',
          'module_id' => 3,
          'display_name' => 'Browse Unit'
        ],['id' => '16',
          'key' => 'view_unit_product',
          'module_id' => 3,
          'display_name' => 'View Unit'
        ],['id' => '17',
          'key' => 'add_unit_product',
          'module_id' => 3,
          'display_name' => 'Create Unit'
        ],['id' => '18',
          'key' => 'edit_unit_product',
          'module_id' => 3,
          'display_name' => 'Edit Unit'
        ],['id' => '19',
          'key' => 'delete_unit_product',
          'module_id' => 3,
          'display_name' => 'Delete Unit'
        ],['id' => '20',
          'key' => 'browse_category_product',
          'module_id' => 3,
          'display_name' => 'Browse Category'
        ],['id' => '21',
          'key' => 'view_category_product',
          'module_id' => 3,
          'display_name' => 'View Category'
        ],['id' => '22',
          'key' => 'add_category_product',
          'module_id' => 3,
          'display_name' => 'Create Category'
        ],['id' => '23',
          'key' => 'edit_category_product',
          'module_id' => 3,
          'display_name' => 'Edit Category'
        ],['id' => '24',
          'key' => 'delete_category_product',
          'module_id' => 3,
          'display_name' => 'Delete Category'
        ],['id' => '25',
          'key' => 'browse_warehouse',
          'module_id' => 4,
          'display_name' => 'Browse Warehouse'
        ],['id' => '26',
          'key' => 'view_warehouse',
          'module_id' => 4,
          'display_name' => 'View Warehouse'
        ],['id' => '27',
          'key' => 'add_warehouse',
          'module_id' => 4,
          'display_name' => 'Add Warehouse'
        ],['id' => '28',
          'key' => 'edit_warehouse',
          'module_id' => 4,
          'display_name' => 'Edit Warehouse'
        ],['id' => '29',
          'key' => 'browse_wareproducts_warehouse',
          'module_id' => 4,
          'display_name' => 'Warehouse Products'
        ],['id' => '30',
          'key' => 'add_wareproducts_warehouse',
          'module_id' => 4,
          'display_name' => 'Insert Warehouse Products'
        ],['id' => '31',
          'key' => 'browse_bank',
          'module_id' => 5,
          'display_name' => 'Browse Bank'
        ],['id' => '32',
          'key' => 'view_bank_bank',
          'module_id' => 5,
          'display_name' => 'View Bank'
        ],['id' => '33',
          'key' => 'edit_bank_bank',
          'module_id' => 5,
          'display_name' => 'Edit Bank'
        ],['id' => '34',
          'key' => 'add_bank_bank',
          'module_id' => 5,
          'display_name' => 'Add Bank'
        ],['id' => '35',
          'key' => 'delete_bank_bank',
          'module_id' => 5,
          'display_name' => 'Delete Bank'
        ],['id' => '36',
          'key' => 'browse_transaction_bank',
          'module_id' => 5,
          'display_name' => 'Browse Bank Transactions'
        ],['id' => '37',
          'key' => 'browse_ledger_bank',
          'module_id' => 5,
          'display_name' => 'Browse Bank Ledger'
        ],['id' => '38',
          'key' => 'browse_customer',
          'module_id' => 6,
          'display_name' => 'Browse Customer Module'
        ],['id' => '39',
          'key' => 'view_customer_customer',
          'module_id' => 6,
          'display_name' => 'View Customer'
        ],['id' => '40',
          'key' => 'edit_customer_customer',
          'module_id' => 6,
          'display_name' => 'Edit Bank'
        ],['id' => '41',
          'key' => 'add_customer_customer',
          'module_id' => 6,
          'display_name' => 'Add New Customer'
        ],['id' => '42',
          'key' => 'browse_customerledger_customer',
          'module_id' => 6,
          'display_name' => 'Browse Customer Ledger'
        ],['id' => '43',
          'key' => 'browse_creditcustomer_customer',
          'module_id' => 6,
          'display_name' => 'Browse Credit Customer'
        ],['id' => '44',
          'key' => 'browse_paidcustomer_customer',
          'module_id' => 6,
          'display_name' => 'Browse Paid Customer'
        ],['id' => '45',
          'key' => 'browse_advancecustomer_customer',
          'module_id' => 6,
          'display_name' => 'Browse Customer Advance'
        ],['id' => '46',
          'key' => 'browse_seller',
          'module_id' => 7,
          'display_name' => 'Browse Seller Module'
        ],['id' => '47',
          'key' => 'add_sells_seller',
          'module_id' => 7,
          'display_name' => 'Add Sell Request'
        ],['id' => '48',
          'key' => 'view_prodreq_warehouse',
          'module_id' => 4,
          'display_name' => 'View Product Request'
        ],['id' => '49',
          'key' => 'view_sales_seller',
          'module_id' => 7,
          'display_name' => 'Manage Sales'
        ],['id' => '50',
          'key' => 'add_collection_seller',
          'module_id' => 7,
          'display_name' => 'Collection'
        ],['id' => '51',
          'key' => 'delete_customer_customer',
          'module_id' => 6,
          'display_name' => 'Delete Customer'
        ],['id' => '52',
          'key' => 'browse_supplier',
          'module_id' => 9,
          'display_name' => 'Browse Supplier Module'
        ],['id' => '53',
          'key' => 'view_supplier_supplier',
          'module_id' => 9,
          'display_name' => 'View Suppliers'
        ],['id' => '54',
          'key' => 'edit_supplier_supplier',
          'module_id' => 9,
          'display_name' => 'Edit Suppliers'
        ],['id' => '55',
          'key' => 'add_supplier_supplier',
          'module_id' => 9,
          'display_name' => 'Add New Supplier'
        ],['id' => '56',
          'key' => 'delete_supplier_supplier',
          'module_id' => 9,
          'display_name' => 'Delete Suppliers'
        ],['id' => '57',
          'key' => 'browse_supplierledger_supplier',
          'module_id' => 9,
          'display_name' => 'Browse Supplier Ledger'
        ],['id' => '58',
          'key' => 'browse_advancesupplier_supplier',
          'module_id' => 9,
          'display_name' => 'Browse Supplier Advance'
        ],['id' => '59',
          'key' => 'browse_fiscalyears',
          'module_id' => 11,
          'display_name' => 'Browse Fiscal Years'
        ],['id' => '60',
          'key' => 'view_fiscalyears',
          'module_id' => 11,
          'display_name' => 'View Fiscal Years'
        ],['id' => '61',
          'key' => 'edit_fiscalyears',
          'module_id' => 11,
          'display_name' => 'Edit Fiscal Years'
        ],
        ['id' => '62',
          'key' => 'delete_fiscalyears',
          'module_id' => 11,
          'display_name' => 'Delete Fiscal Years'
        ], 
        
      ]);
    }
}
